### ISSUE TITLE
side navigation with hint title

### ISSUE THREAD

**Issue by ahmed205** [almeida-matheus/fullPageScrollPureJS#1]
Hi

i was wonder if it can add hint title while mouse over in the dot navigation ex. home, about, etc ?

**Comment by almeida-matheus** [comment]
Yes!!! my friend is working for resolve that. Will be available in the next release. Thanks!!!

**Comment by amendoa** [comment]
Hi!
That would be nice! I'll work on this when possible, but feel free to open a pull request! Thanks!
