### ISSUE TITLE
double scrolls on macOS

### ISSUE THREAD

**Issue by mariomesiti** [almeida-matheus/fullPageScrollPureJS#7]
Hi there, on macOs one mouse scroll makes fullpage scroll twice. Same with trackpad gesture. Tested on macOS 10.15.5 with Chrome, Firefox or Safari. Test page is: https://fullpagescrollpurejs.surge.sh/

**Comment by mariomesiti** [comment]
Hi there, have you got news on the subject? Any idea on when the issue will be fixed? Thank you

**Comment by amendoa** [comment]
Hey Buddy! Actually I don't. I'm gonna try to use my free time as soon as possible to investigate that, but feel free to submit a pull request. Thanks for reporting!
